#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Set default editor to vim
export VISUAL=vim

# Color ls
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

# Customize to your needs...
alias ls='ls -alh'

# setup thefuck alias, https://github.com/nvbn/thefuck
if command -v fuck >/dev/null 2>&1; then
  eval $(thefuck --alias)
fi

# setup rbenv if available
if command -v rbenv >/dev/null 2>&1; then
  eval "$(rbenv init -)"
fi

