#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Color ls
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

# Go env vars
if command -v go &>/dev/null; then
  go env -w GOPATH=$HOME/go
fi

# setup rbenv if available
if command -v rbenv &>/dev/null; then
  eval "$(rbenv init -)"
fi

# setup HashiCorp VagrantCloud (used to be Atlas)
if [[ -s "${HOME}/.vagrantcloud" ]]; then
  export ATLAS_TOKEN=$(cat $HOME/.vagrantcloud)
fi

# setup kubectl autocompletion
if [ $commands[kubectl] ]; then
  source <(kubectl completion zsh);
fi

# Aliases
alias gotree="tree -I vendor"
